#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

BASELINE_FILE="${ROOT_DIR}/scripts/perf/baseline.env"
METRICS_OUT="${ROOT_DIR}/target/perf-metrics.env"
REGRESSION_FACTOR="${PERF_REGRESSION_FACTOR:-2.0}"

bench_keys=(
  "apply_filter_flat"
  "apply_filter_grouped"
  "render_frame_main"
  "index_cache_load_validate"
)

extract_point_estimate() {
  local key="$1"
  local estimate_file="${ROOT_DIR}/target/criterion/${key}/new/estimates.json"
  if [[ ! -f "$estimate_file" ]]; then
    echo "missing benchmark estimate: $estimate_file" >&2
    return 1
  fi
  grep -o '"point_estimate":[0-9.e+-]*' "$estimate_file" | head -n 1 | cut -d: -f2
}

stat_size_bytes() {
  local path="$1"
  if stat -c%s "$path" >/dev/null 2>&1; then
    stat -c%s "$path"
  else
    stat -f%z "$path"
  fi
}

echo "Running perf benchmarks..."
cargo bench --locked --bench perf_core -- --sample-size 20 --noplot

mkdir -p "$(dirname "$METRICS_OUT")"
{
  echo "# Auto-generated by scripts/perf/gate.sh"
  for key in "${bench_keys[@]}"; do
    value="$(extract_point_estimate "$key")"
    upper_key="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
    echo "CURRENT_${upper_key}_NS=${value}"
  done
} >"$METRICS_OUT"

echo "Building distribution binary for size gate..."
cargo build --profile release-dist --locked
BIN_PATH="${ROOT_DIR}/target/release-dist/cosmos"
BIN_SIZE="$(stat_size_bytes "$BIN_PATH")"
echo "CURRENT_RELEASE_DIST_BYTES=${BIN_SIZE}" >>"$METRICS_OUT"

if [[ ! -f "$BASELINE_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$METRICS_OUT"
  max_bytes="$(awk -v b="$CURRENT_RELEASE_DIST_BYTES" 'BEGIN { printf "%.0f", b * 1.10 }')"
  {
    echo "# Baseline created by scripts/perf/gate.sh"
    for key in "${bench_keys[@]}"; do
      upper_key="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
      current_var="CURRENT_${upper_key}_NS"
      echo "${upper_key}_NS=${!current_var}"
    done
    echo "RELEASE_DIST_BYTES=${CURRENT_RELEASE_DIST_BYTES}"
    echo "RELEASE_DIST_MAX_BYTES=${max_bytes}"
  } >"$BASELINE_FILE"
  echo "Baseline created at $BASELINE_FILE"
  echo "Re-run the gate to enforce thresholds."
  exit 0
fi

# shellcheck disable=SC1090
source "$BASELINE_FILE"
# shellcheck disable=SC1090
source "$METRICS_OUT"

fail=0
for key in "${bench_keys[@]}"; do
  upper_key="$(echo "$key" | tr '[:lower:]' '[:upper:]')"
  baseline_var="${upper_key}_NS"
  current_var="CURRENT_${upper_key}_NS"
  current="${!current_var:-}"
  baseline="${!baseline_var:-}"

  if [[ -z "${current}" || -z "${baseline}" ]]; then
    echo "Missing benchmark value for ${baseline_var}" >&2
    fail=1
    continue
  fi

  limit="$(awk -v b="$baseline" -v f="$REGRESSION_FACTOR" 'BEGIN { printf "%.6f", b * f }')"
  regressed="$(awk -v c="$current" -v l="$limit" 'BEGIN { if (c > l) print 1; else print 0 }')"
  echo "${key}: current=${current}ns baseline=${baseline}ns limit=${limit}ns"
  if [[ "$regressed" == "1" ]]; then
    echo "Regression detected in ${key}" >&2
    fail=1
  fi
done

max_bytes="${RELEASE_DIST_MAX_BYTES:-${RELEASE_DIST_BYTES:-0}}"
if [[ "$max_bytes" -le 0 ]]; then
  echo "Missing RELEASE_DIST_MAX_BYTES/RELEASE_DIST_BYTES baseline." >&2
  fail=1
else
  echo "release-dist size: current=${CURRENT_RELEASE_DIST_BYTES} max=${max_bytes}"
  if [[ "${CURRENT_RELEASE_DIST_BYTES}" -gt "${max_bytes}" ]]; then
    echo "Binary size regression detected (${CURRENT_RELEASE_DIST_BYTES} > ${max_bytes})" >&2
    fail=1
  fi
fi

if [[ "$fail" -ne 0 ]]; then
  echo "Performance gate failed." >&2
  exit 1
fi

echo "Performance gate passed."
